name = "Direction Arrow"
directory = "direction_arrow"
author = "Alihan"
license = "CC-BY-4.0"
license_source = "http://creativecommons.org/licenses/by/4.0/"
source = "https://sketchfab.com/3d-models/direction-arrow-6ef46718c7b242e39fcad7f27ee858a5"
ty = "art"
custom_attribution = "\"Direction Arrow\" (https://skfb.ly/ozHGW) by Alihan is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/)."
