name = "Wintery loop"
directory = "wintery_loop_music"
author = "Emma_MA"
license = "CC0"
license_source = "https://creativecommons.org/publicdomain/zero/1.0/"
source = "https://opengameart.org/content/wintery-loop"
ty = "music"
