name = "Holiday Kit"
directory = "kenney_holiday-kit"
author = "Kenney"
license = "CC0"
license_source = "https://creativecommons.org/publicdomain/zero/1.0/"
source = "https://kenney.nl/assets/holiday-kit"
ty = "art"
