name = "Erratic Cursive Font - CC0"
directory = "ErraticCursive_Font_1_0"
author = "GGBotNet"
license = "CC0"
license_source = "https://creativecommons.org/publicdomain/zero/1.0/"
source = "https://ggbot.itch.io/erratic-cursive-font"
ty = "fonts"
