name = "Particle Pack"
directory = "kenney_particle-pack"
author = "Kenney"
license = "CC0"
license_source = "https://creativecommons.org/publicdomain/zero/1.0/"
source = "https://www.kenney.nl/assets/particle-pack"
ty = "art"
