name = "Snowland Town"
directory = "Snowland_Collection"
author = "Matthew Pablo"
license = "CC BY-SA 3.0"
license_source = "https://creativecommons.org/licenses/by-sa/3.0/"
source = "https://opengameart.org/content/snowland-town"
ty = "music"
