name = "Old Parchment Paper"
directory = "old_parchment_paper"
author = "cron"
license = "CC0"
license_source = "https://creativecommons.org/publicdomain/zero/1.0/"
source = "https://opengameart.org/content/old-parchment-paper"
ty = "art"
