name: Build and Release

on:
  release:
    types: [published]

env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  CARGO_TERM_COLOR: always
  ITCH_GAME: project-reindeer
  ITCH_USER: andersgaustad

jobs:
  cargo-build:
    name : Cargo Build - ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
          
      - name: Build
        run: cargo build --release --verbose

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: raw-rust-build-${{ matrix.os }}
          path: target/release/*project*reindeer*
    
  godot-export-and-release:
    needs: cargo-build
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v6
        with:
          lfs: true
      
      - name: Install Dependencies
        run: |
            apt-get update && \
            apt-get install -y \
                build-essential \
                clang \
                curl \
                gcc-multilib \
                python3

      - name: Setup Rust
        # We need to setup Rust here as well to register classes and import them for the export to work.
        # See below.
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
    
      - name: Register Classes
        # Note that this will create a debug build of the Rust code,
        # and only for Linux.
        # Needed for importing class names, see below.
        run: cargo build

      - name: Extract Version
        # Version is used by Butler's Upload to itchio Action
        run: |
          VERSION=${{ github.ref_name }}
          echo "Release Version: $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        
      - name: Setup Directories
        run: |
          mkdir -v -p target/release
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
      
      - name: Download
        uses: actions/download-artifact@v7
        with:
          path: target/release
          merge-multiple: true
      
      - name: Import Registered Classes
        # For some reason, class names are only registered from debug builds for Linux.
        # Thus, we must (as far as I know at least) create a debug build and import before exporting.
        # Note that the debug build itself is not exported.
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --import 

      - name: Export - ${{ vars.LINUX_NAME }}
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.LINUX_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}.x86_64"

      - name: Butler Push - ${{ vars.LINUX_NAME }}
        uses: yeslayla/butler-publish-itchio-action@v1.2.0
        env:
          CHANNEL: ${{ vars.LINUX_NAME }}
          PACKAGE: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}

      - name: Upload - ${{ vars.LINUX_NAME }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}

      - name: Export - ${{ vars.WINDOWS_NAME }}
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.WINDOWS_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}.exe"
    
      - name: Butler Push - ${{ vars.WINDOWS_NAME }}
        uses: yeslayla/butler-publish-itchio-action@v1.2.0
        env:
          CHANNEL: ${{ vars.WINDOWS_NAME }}
          PACKAGE: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}

      - name: Upload - ${{ vars.WINDOWS_NAME }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}

      - name: Export - ${{ vars.MAC_OS_NAME }}
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.MAC_OS_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}.zip"

      - name: Butler Push - ${{ vars.MAC_OS_NAME }}
        uses: yeslayla/butler-publish-itchio-action@v1.2.0
        env:
          CHANNEL: ${{ vars.MAC_OS_NAME }}
          PACKAGE: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
        
      - name: Upload - ${{ vars.MAC_OS_NAME }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
