name: Build and Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    name : Cargo Build - ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
          
      - name: Build
        run: cargo build --release --verbose

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-raw-rust-build
          path: target/release/*project*reindeer*
    
  godot-export:
    needs: cargo-build
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p target/release
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
      
      - name: Download
        uses: actions/download-artifact@v7
        with:
          path: target/release
          merge-multiple: true

      - name: Showing Directory
        run: |
          echo "In root:"
          ls
          echo "In target/"
          ls target
          echo "In target/release/"
          ls target/release
        
      - name: Build Linux
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.LINUX_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}.x86_64"

      - name: Upload Linux
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}

      - name: Build Windows
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.WINDOWS_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}.exe"

      - name: Upload Windows
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}

      - name: Build Mac
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.MAC_OS_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}.zip"
        
      - name: Upload MacOS
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
