name: Test WASM

on:
  push:
    branches: ["web"]

env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  CARGO_TERM_COLOR: always
  ITCH_GAME: project-reindeer
  ITCH_USER: andersgaustad

jobs:
  test-wasm-release:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v6
        with:
          lfs: true
      
      - name: Install Dependencies
        run: |
            apt-get update && \
            apt-get install -y \
                build-essential \
                curl \
                gcc-multilib \
                libclang-dev \
                python3

      - name: Setup Rust
        # We need to setup Rust here as well to register classes and import them for the export to work.
        # See below.
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
    
      - name: Add WASM Cargo target
        run: |
            rustup toolchain install nightly
            rustup component add rust-src --toolchain nightly
            rustup target add wasm32-unknown-emscripten --toolchain nightly
    
      - name: Setup Emscripten toolchain
        uses: emscripten-core/setup-emsdk@v16
        with:
            version: 3.1.74
            actions-cache-folder: 'emsdk-cache'

      - name: Check emcc
        run: emcc --version

      - name: Modify Cargo.toml
        run: mv rust-project-reindeer/Cargo.wasm.toml rust-project-reindeer/Cargo.toml

      - name: Register Classes
        # Note that this will create a debug build of the Rust code,
        # and only for Linux.
        # Needed for importing class names, see below.
        run: GODOT4_BIN=$(which godot) cargo build

      - name: Build Web
        run: |
            RUSTFLAGS="-C link-args=-pthread \
                -C target-feature=+atomics \
                -C link-args=-sSIDE_MODULE=2 \
                -C llvm-args=-enable-emscripten-cxx-exceptions=0 \
                -Z default-visibility=hidden \
                -Z link-native-libraries=no \
                -Z emscripten-wasm-eh=false \
                -Z unstable-options" \
                GODOT4_BIN=$(which godot) \
                cargo +nightly build -r -Zbuild-std --target wasm32-unknown-emscripten

      - name: Extract Version
        # Version is used by Butler's Upload to itchio Action
        run: |
          VERSION="v0.1.0-build-test"
          echo "Release Version: $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        
      - name: Setup Directories
        run: |
          mkdir -v -p target/release
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.LINUX_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.MAC_OS_NAME }}
          mkdir -v -p ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WEB_W_THREADS_NAME }}
      
      - name: Download
        uses: actions/download-artifact@v7
        with:
          path: target/release
          merge-multiple: true
      
      - name: Import Registered Classes
        # For some reason, class names are only registered from debug builds for Linux.
        # Thus, we must (as far as I know at least) create a debug build and import before exporting.
        # Note that the debug build itself is not exported.
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --import 

      - name: Export - ${{ vars.WEB_W_THREADS_NAME }}
        run: godot --headless --verbose --path "${{ vars.PROJECT_PATH }}" --export-release "${{ vars.WEB_W_THREADS_NAME }}" "build/${{ vars.EXPORT_NAME }}-${{ vars.WINDOWS_NAME }}/index.html"

      - name: Butler Push - ${{ vars.WEB_W_THREADS_NAME }}
        uses: yeslayla/butler-publish-itchio-action@v1.2.0
        env:
          CHANNEL: ${{ vars.WEB_W_THREADS_NAME }}
          PACKAGE: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WEB_W_THREADS_NAME }}
      
      - name: Upload - ${{ vars.WEB_W_THREADS_NAME }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXPORT_NAME }}-${{ vars.WEB_W_THREADS_NAME }}
          path: ${{ vars.PROJECT_PATH }}/build/${{ vars.EXPORT_NAME }}-${{ vars.WEB_W_THREADS_NAME }}
